project:
  output-dir: docs
  render:
    - index.qmd
    - templates/dashboard/index.qmd
    - templates/presentation/index.qmd
    - templates/report/index.qmd
    - templates/typst-pdf/index.qmd
    - templates/confluence/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - scss/quarto-theme.scss
    toc: true
    toc-depth: 3
    number-sections: true
    lang: ko
    favicon: assets/brand/favicon.svg
