project:
  output-dir: docs
  render:
    - templates/dashboard/index.qmd
    - templates/presentation/index.qmd
    - templates/report/index.qmd
    - templates/typst-pdf/index.qmd

format:
  html:
    theme:
      - cosmo
      - scss/quarto-theme.scss
    toc: true
    toc-depth: 3
    number-sections: true
    lang: ko
    mainfont: "Pretendard Variable"
    monofont: "JetBrains Mono"
    favicon: design-system/brand/favicon.svg
