project:
  output-dir: ../../docs/templates/typst-pdf

brand: ../../_brand.yml

format:
  typst:
    lang: ko
    monofont: "D2Coding ligature"
    toc: true
    number-sections: true
    margin:
      x: 2.5cm
      y: 2.5cm
    fontsize: 11pt
    linestretch: 1.5
    columns: 1
