project:
  type: book
  output-dir: ../../docs/templates/book

brand: ../../_brand.yml

book:
  title: "책 제목"
  author: "저자명"
  date: today
  date-format: "YYYY년 MM월 DD일"
  sidebar:
    logo: logo-text.svg
  chapters:
    - index.qmd
    - chapter-01.qmd
    - chapter-02.qmd
  downloads: [pdf]

format:
  html:
    theme:
      - cosmo
      - brand
      - ../../scss/quarto-theme.scss
    lang: ko
    favicon: ../../assets/brand/favicon.svg
    toc: true
    number-sections: true
  typst:
    lang: ko
    monofont: "D2Coding ligature"
    toc: true
    number-sections: true
    margin:
      x: 2.5cm
      y: 2.5cm
    fontsize: 11pt
    linestretch: 1.5
    columns: 1
